/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions.$sessionId'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports.$reportId'
import { Route as AuthenticatedPracticeNewRouteImport } from './routes/_authenticated/practice.new'
import { Route as AuthenticatedPracticeSessionIdRouteImport } from './routes/_authenticated/practice.$sessionId'
import { Route as AuthenticatedPracticeSessionIdAvatarRouteImport } from './routes/_authenticated/practice.$sessionId.avatar'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeNewRoute =
  AuthenticatedPracticeNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedPracticeSessionIdRoute =
  AuthenticatedPracticeSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedPracticeSessionIdAvatarRoute =
  AuthenticatedPracticeSessionIdAvatarRouteImport.update({
    id: '/avatar',
    path: '/avatar',
    getParentRoute: () => AuthenticatedPracticeSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/practice/$sessionId': typeof AuthenticatedPracticeSessionIdRouteWithChildren
  '/practice/new': typeof AuthenticatedPracticeNewRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/practice/$sessionId/avatar': typeof AuthenticatedPracticeSessionIdAvatarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/practice/$sessionId': typeof AuthenticatedPracticeSessionIdRouteWithChildren
  '/practice/new': typeof AuthenticatedPracticeNewRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/practice/$sessionId/avatar': typeof AuthenticatedPracticeSessionIdAvatarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/_authenticated/practice/$sessionId': typeof AuthenticatedPracticeSessionIdRouteWithChildren
  '/_authenticated/practice/new': typeof AuthenticatedPracticeNewRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/_authenticated/practice/$sessionId/avatar': typeof AuthenticatedPracticeSessionIdAvatarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/practice'
    | '/practice/$sessionId'
    | '/practice/new'
    | '/reports/$reportId'
    | '/sessions/$sessionId'
    | '/practice/$sessionId/avatar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/practice'
    | '/practice/$sessionId'
    | '/practice/new'
    | '/reports/$reportId'
    | '/sessions/$sessionId'
    | '/practice/$sessionId/avatar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/practice'
    | '/_authenticated/practice/$sessionId'
    | '/_authenticated/practice/new'
    | '/_authenticated/reports/$reportId'
    | '/_authenticated/sessions/$sessionId'
    | '/_authenticated/practice/$sessionId/avatar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/new': {
      id: '/_authenticated/practice/new'
      path: '/new'
      fullPath: '/practice/new'
      preLoaderRoute: typeof AuthenticatedPracticeNewRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/practice/$sessionId': {
      id: '/_authenticated/practice/$sessionId'
      path: '/$sessionId'
      fullPath: '/practice/$sessionId'
      preLoaderRoute: typeof AuthenticatedPracticeSessionIdRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/practice/$sessionId/avatar': {
      id: '/_authenticated/practice/$sessionId/avatar'
      path: '/avatar'
      fullPath: '/practice/$sessionId/avatar'
      preLoaderRoute: typeof AuthenticatedPracticeSessionIdAvatarRouteImport
      parentRoute: typeof AuthenticatedPracticeSessionIdRoute
    }
  }
}

interface AuthenticatedPracticeSessionIdRouteChildren {
  AuthenticatedPracticeSessionIdAvatarRoute: typeof AuthenticatedPracticeSessionIdAvatarRoute
}

const AuthenticatedPracticeSessionIdRouteChildren: AuthenticatedPracticeSessionIdRouteChildren =
  {
    AuthenticatedPracticeSessionIdAvatarRoute:
      AuthenticatedPracticeSessionIdAvatarRoute,
  }

const AuthenticatedPracticeSessionIdRouteWithChildren =
  AuthenticatedPracticeSessionIdRoute._addFileChildren(
    AuthenticatedPracticeSessionIdRouteChildren,
  )

interface AuthenticatedPracticeRouteChildren {
  AuthenticatedPracticeSessionIdRoute: typeof AuthenticatedPracticeSessionIdRouteWithChildren
  AuthenticatedPracticeNewRoute: typeof AuthenticatedPracticeNewRoute
}

const AuthenticatedPracticeRouteChildren: AuthenticatedPracticeRouteChildren = {
  AuthenticatedPracticeSessionIdRoute:
    AuthenticatedPracticeSessionIdRouteWithChildren,
  AuthenticatedPracticeNewRoute: AuthenticatedPracticeNewRoute,
}

const AuthenticatedPracticeRouteWithChildren =
  AuthenticatedPracticeRoute._addFileChildren(
    AuthenticatedPracticeRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRouteWithChildren
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRoute
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRouteWithChildren,
  AuthenticatedReportsReportIdRoute: AuthenticatedReportsReportIdRoute,
  AuthenticatedSessionsSessionIdRoute: AuthenticatedSessionsSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
